version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout:

      - run:
          name: Build
          command: docker run -v $PWD:/toggleR -w /toggleR --env TOGGL_TOKEN --env TOGGL_WORKSPACE praqma/toggler:0.2.2.5 Rscript use-toggler.R

      - run:
          name: Html
          command: ./html.sh

      - store_artifacts:
          path: this-month

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 8,16 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
