version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout:

      - run:
          name: Build
          command: docker run -v $PWD:/toggleR -w /toggleR --env TOGGL_TOKEN --env TOGGL_WORKSPACE drbosse/toggler:0.3.0.5 Rscript use-toggler.R

      - run:
          name: Html
          command: ./html.sh

      - store_artifacts:
          path: this-month

      - store_artifacts:
          path: last-month

workflows:
  version: 2
  commit:
    jobs:
      - build
  daily:
    triggers:
      - schedule:
          cron: "0 8,16 * * 1-5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
